## Creating NumPy Arrays


In [6]:
import numpy as np
#create 1d array of integers from 1 to 10
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array)
print(type(array))
print(array.shape)
print(array.dtype)
arr= np.arange(1, 11)
print(arr)
# a 2d array of shape(3,3) with values  from 1 to 9
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)
print(array_2d.shape)
print(array_2d.dtype)
arr_2d = np.arange(1, 10).reshape(3, 3)
print(arr_2d)
print(arr_2d.shape)
print(arr_2d.dtype)
# a 3d array of shape (2,2,2) with values from 1 to 8   
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d) 
arr_3d = np.arange(1, 9).reshape(2, 2, 2)
print(arr_3d)
# a numpy array from list:[10,20,30,40,50]
array_from_list = np.array([10, 20, 30, 40, 50])
print(array_from_list)  

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)
int64
[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[10 20 30 40 50]


## Task2 Important mathematical operations

In [10]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])
"""Perform and print results for
print(A + B)  # Addition
print(A - B)  # Subtraction
print(A * B)  # Element-wise multiplication
print(A / B)  # Element-wise division   
print(A ** B)  # Element-wise exponentiation
print(A % B)  # Element-wise modulus

"""
print(A + B)  # Addition
print(A - B)  # Subtraction
print(A * B)  # Element-wise multiplication
print(A / B)  # Element-wise division
print(A ** B)  # Element-wise exponentiation
print(A **2)  # Element-wise exponentiation
print(A % B)  # Element-wise modulus

#use numpy functions to perform the following operations on array A:
print(np.sum(A))  # Sum of all elements
print(np.mean(A))  # Mean of all elements
print(np.median(A))  # Median of all elements
print(np.std(A))  # Standard deviation of all elements
print(np.var(A))  # Variance of all elements

print(np.add(A, B))  # Sum of all elements
print(np.subtract(A, B))  # Mean of all elements
print(np.multiply(A, B))  # Median of all elements
print(np.divide(A, B))  # Standard deviation of all elements
print(np.power(A, B))  # Variance of all elements


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]
[ 100  400  900 1600]
[0 0 0 0]
100
25.0
25.0
11.180339887498949
125.0
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]


## Task 3 Numpy Mathematical formulas


In [12]:
values = np.array([2,4,6,8,10])
##calculate root of each element in values
print(np.sqrt(values))
##Exponential of each element in values
print(np.exp(values))
##LNatural Logarithm of each element in values
print(np.log(values))
## Sum of all elements in values
print(np.sum(values))
## Mean of all elements in values
print(np.mean(values))
## Cumulative sum of elements in values
print(np.cumsum(values))


[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
30
6.0
[ 2  6 12 20 30]


## Task 4 Aggregation operations

In [13]:
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
## calculate row-wise sum of data
print(np.sum(data, axis=1))
## calculate column-wise mean of data
print(np.mean(data, axis=0))
## calculate cumulative product along rows of data
print(np.cumprod(data, axis=1))
## calculate minimum and maximum values in data
print(np.min(data))
print(np.max(data))
## calculate overall mean of data
print(np.mean(data))

[ 60 150 240]
[40. 50. 60.]
[[    10    200   6000]
 [    40   2000 120000]
 [    70   5600 504000]]
10
90
50.0


## Task 5 Statistical operations code focus

In [14]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
## calculate mean, median, and standard deviation, variance, minimum
## maximum, Range(Max - min)
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))
print(np.var(marks))
print(np.min(marks))
print(np.max(marks))
print(np.max(marks) - np.min(marks))


79.25
81.5
11.583932838203095
134.1875
60
95
35


## Task 6 - Percentile  & Sorting

In [15]:
## using same marks array,
## 1. sort the array
## 2. find 25th , 50th , 75th percentiles
## 3. count how many srudents scored above avg

sorted_marks = np.sort(marks)
print(sorted_marks)
percentiles = np.percentile(marks, [25, 50, 75])
print(percentiles)
average = np.mean(marks)
above_avg_count = np.sum(marks > average)
print(above_avg_count)


[60 66 72 78 85 88 90 95]
[70.5 81.5 88.5]
4


## Task 7 - Mini use case Sales Analysis

In [16]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
## Perform the following operations on sales array:
## 1. Total weekly sales
## 2. Average daily sales
## 3. Highest & lowest sales day
## 4. Identify days where sales were above average  

total_weekly_sales = np.sum(sales)
average_daily_sales = np.mean(sales)
highest_sales = np.max(sales)
lowest_sales = np.min(sales)
above_average_days = np.where(sales > average_daily_sales)[0]
print("Total Weekly Sales:", total_weekly_sales)
print("Average Daily Sales:", average_daily_sales)
print("Highest Sales Day:", highest_sales)
print("Lowest Sales Day:", lowest_sales)
print("Days with Above Average Sales:", above_average_days)


Total Weekly Sales: 10700
Average Daily Sales: 1528.5714285714287
Highest Sales Day: 2000
Lowest Sales Day: 900
Days with Above Average Sales: [3 4 5 6]
